# Generated by Django 3.2.19 on 2023-06-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='addres',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ادرس'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar_user', verbose_name='عکس پروفایل'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='بیوگرافی'),
        ),
    ]
