# Generated by Django 3.2.19 on 2023-06-26 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان وبلاگ')),
                ('short_description', models.TextField(verbose_name='توضیح کوتاه')),
                ('img', models.ImageField(upload_to='blog', verbose_name='عکس')),
                ('subject1', models.TextField(verbose_name='موضوع 1')),
                ('subtext1', models.TextField(verbose_name='متن 1')),
                ('subject2', models.TextField(verbose_name='موضوع 2')),
                ('subtext2', models.TextField(verbose_name='متن 2')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='زمان انتشار')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیر فعال')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقاله ها',
            },
        ),
    ]
