# Generated by Django 3.2.19 on 2023-07-03 15:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_articlecomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleComment',
            new_name='BlogComment',
        ),
    ]
