# Generated by Django 3.2.19 on 2023-07-03 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_articlecomment_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='article',
            new_name='blog',
        ),
    ]
