# Generated by Django 3.2.19 on 2023-06-26 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_estate_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorys', models.CharField(max_length=10, verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.AlterModelOptions(
            name='propertytype',
            options={'verbose_name': 'نوع', 'verbose_name_plural': 'نوع ملک'},
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='types',
            field=models.CharField(max_length=20, verbose_name='نوع ملک'),
        ),
        migrations.AddField(
            model_name='estate',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estate.category', verbose_name='دسته بندی'),
        ),
    ]
