# Generated by Django 3.2.19 on 2023-06-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0005_estate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ادرس ملک'),
        ),
    ]
