# Generated by Django 3.2.19 on 2023-06-26 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0008_auto_20230626_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.state', verbose_name='استان'),
        ),
    ]
