# Generated by Django 3.2.19 on 2023-06-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0009_alter_estate_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='year_of_construction',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True, verbose_name='سال ساخت'),
        ),
    ]
