# Generated by Django 3.2.19 on 2023-06-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0010_estate_year_of_construction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='year_of_construction',
            field=models.PositiveIntegerField(max_length=4, verbose_name='سال ساخت'),
        ),
    ]
