# Generated by Django 3.2.19 on 2023-06-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0011_alter_estate_year_of_construction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='year_of_construction',
            field=models.PositiveIntegerField(verbose_name='سال ساخت'),
        ),
    ]
