# Generated by Django 3.2.19 on 2023-06-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0012_alter_estate_year_of_construction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, verbose_name='عنوان در url'),
        ),
    ]
