# Generated by Django 3.2.19 on 2023-07-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0014_auto_20230717_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url_title',
            field=models.SlugField(max_length=200, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='url_title',
            field=models.SlugField(max_length=200, verbose_name='url'),
        ),
    ]
