# Generated by Django 3.2.19 on 2023-07-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0015_auto_20230717_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelfareAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='امکانات رفاهی')),
            ],
            options={
                'verbose_name': 'امکانات',
                'verbose_name_plural': 'امکانات رفاهی',
            },
        ),
    ]
