# Generated by Django 3.2.19 on 2023-07-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0017_auto_20230731_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='پارکینگ'),
        ),
    ]
