# Generated by Django 3.2.19 on 2023-07-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0019_sendvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='welfare_amenities',
            field=models.ManyToManyField(to='estate.WelfareAmenities', verbose_name='امکانات'),
        ),
    ]
