# Generated by Django 3.2.19 on 2023-08-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0020_estate_welfare_amenities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estate',
            old_name='Meterage',
            new_name='meterage',
        ),
        migrations.AlterField(
            model_name='sendvisit',
            name='phone',
            field=models.PositiveIntegerField(verbose_name='شماره'),
        ),
    ]
