# Generated by Django 3.2.19 on 2023-08-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0021_auto_20230807_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
