# Generated by Django 3.2.19 on 2023-08-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0021_auto_20230807_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='parking',
            field=models.BooleanField(choices=[(True, 'دارد'), (False, 'ندارد')], verbose_name='پارکینگ'),
        ),
    ]
