# Generated by Django 3.2.19 on 2023-08-09 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0022_state_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='slug',
        ),
    ]
