# Generated by Django 3.2.19 on 2023-06-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='موبایل'),
        ),
    ]
