# Generated by Django 3.2.19 on 2023-06-14 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='about_gallery', verbose_name='عکس درباره ما')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.about')),
            ],
            options={
                'verbose_name': 'گالری درباره ما',
                'verbose_name_plural': 'گالری درباره ما',
            },
        ),
    ]
