# Generated by Django 3.2.19 on 2023-06-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutgallery',
            name='about',
        ),
    ]
