# Generated by Django 3.2.19 on 2023-06-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_aboutgallery_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutGallery',
        ),
    ]
