# Generated by Django 3.2.19 on 2023-06-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_delete_aboutgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='img',
        ),
        migrations.AddField(
            model_name='about',
            name='img1',
            field=models.ImageField(blank=True, upload_to='about_gallery'),
        ),
        migrations.AddField(
            model_name='about',
            name='img2',
            field=models.ImageField(blank=True, upload_to='about_gallery'),
        ),
    ]
