# Generated by Django 3.2.19 on 2023-06-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20230614_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='img1',
            field=models.ImageField(blank=True, upload_to='about'),
        ),
        migrations.AlterField(
            model_name='about',
            name='img2',
            field=models.ImageField(blank=True, upload_to='about'),
        ),
    ]
