# Generated by Django 3.2.19 on 2023-07-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان تنظیمات')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='لوگو')),
                ('phone', models.PositiveIntegerField(verbose_name='موبایل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('address', models.CharField(max_length=30, verbose_name='ادرس')),
                ('facebook_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='فیسبوک')),
                ('aparat_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='آپارات')),
                ('instagram_url', models.URLField(max_length=500, verbose_name='اینستاگرام')),
                ('telegram_url', models.URLField(max_length=500, verbose_name='تلگرام')),
                ('youtube_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='یوتیوب')),
                ('whatsapp_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='واتساپ')),
                ('main_setting', models.BooleanField(default=False, verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنظیم سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
