# Generated by Django 3.2.19 on 2023-07-03 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان لینک فوتر')),
            ],
            options={
                'verbose_name': 'عنوان لینک فوتر',
                'verbose_name_plural': 'عناوین لینکهای فوتر',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='لینک فوتر')),
                ('url_title', models.URLField(max_length=500, verbose_name='آدرس url لینک')),
                ('footer_link_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_setting.footerlinktitle', verbose_name='عنوان سردسته لینک')),
            ],
            options={
                'verbose_name': 'لینک فوتر',
                'verbose_name_plural': 'لینکهای فوتر',
            },
        ),
    ]
