# Generated by Django 3.2.19 on 2023-07-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0002_footerlink_footerlinktitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='home_baner', verbose_name='بنر اول صفحه اصلی')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان')),
                ('des', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنر صفحه اصلی',
            },
        ),
    ]
